trigger: none

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      displayName: Tf Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'mysc1'
        backendAzureRmResourceGroupName: 'rg_storage_acc'
        backendAzureRmStorageAccountName: 'storageacclakshmi'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.terraform.state'
    - task: TerraformTaskV4@4
      displayName: Tf Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'mysc1'